#! /bin/bash
# Source this file into ~/.bash_profile
# Anything I want to remain consistent between machines goes here.

# I want to use i-search, which is bound to ctrl-s.  Howerver, XOFF, which pauses data transmission,
# is also bound to ctl-s, which is stupid.  Since I live my life through SSH, this isn't great.
stty -ixon  

#alias ls='ls -F --group-directories-first --color=auto'
#alias ll='ls -l'
alias k='kubectl'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# lazy functions to spin up/down gce||gke clusters
source $DIR/k8s-scripts/cluster-do

# custom bash prompt including PS1
source $DIR/bash_prompt

function sprunge(){
	curl -F 'sprunge=<-' http://sprunge.us
}
